---
title: "Figure2"
author: "Yingjie"
date: "10/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


  This script aims to combine sub-plots for Figure 2. 



# Setup 
```{r}
getwd()

library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(viridis)
library(tidyquant)

source('helperFunctions.R') ## mae() function
```



# Data

  Load data from 3 models. 
  
```{r}
## 1. load llModErr and fdaErr --------------------------------------------------------------------
load(file = './data/errDat.Rdata')


## 2. load RF model error data --------------------------------------------------------------------
root <- dirname(getwd())

fname <- paste0(root, '/Dead_Zone_telecoupling/data/results_RF/err_rf_Day_DObottom_2014_2014.Rdata'); fname
load(fname)

acc_set <- 'testing'

### input data for plotting 
acc0 <- err_rf %>%
  gather(key = 'errType', value = 'value', RMSE:R2) %>%
  dplyr::mutate(errType = factor(errType, levels = c('R2', 'RMSE', 'MAE')))

### option 1. use mean, se OR sd,for plotting ----
###   `summarySE` provides the standard deviation, standard error of the mean, and a (default 95%) confidence interval
library(Rmisc)
rfErr <- summarySE(data = acc0, measurevar="value", groupvars=c("year", "nw", "errType")) %>%
  dplyr::select(-year, -N) %>%
  dplyr::rename(lag = nw)



### option 2. use median, max, min for plotting -----
rfErr <- acc0 %>%
  dplyr::select(-year) %>%
  dplyr::rename(lag = nw) %>%
  group_by(lag, errType) %>%
  dplyr::summarise(med = median(value, na.rm = T),
                   max = max(value, na.rm = T), 
                   min = min(value, na.rm = T), 
                   avg = mean(value, na.rm = T),
                   iqr=IQR(value, na.rm = T)) %>%
  dplyr::mutate(withinSampErr = NA)
  


## 3. bind three data sets -------------------------------------------------------------------------

names(fdaErr)
names(llModErr)
names(rfErr)

err_2models <- rbind(llModErr %>% dplyr::mutate(mod = 'LLR'),
                     rfErr    %>% dplyr::mutate(mod = 'RFR')) %>%
  dplyr::mutate(lag = -lag) %>%
  ungroup() %>%
  as.data.frame()
```



# Plot

## plot 1

### median value

  Tried `mean` value too, and it looks `mean` value is easier to identify the *best day*. 
  
```{r}
### highlight the best day for prediction
err_2models_bestday <- err_2models %>% 
  dplyr::mutate(mod = as.factor(mod), errType = as.factor(errType)) %>%
  group_by(mod, errType) %>%
  dplyr::mutate(best    = ifelse(errType != 'R2', min(med), max(med, na.rm = T)),
                bestday = ifelse(med == best, lag, NA)) %>%
  arrange(mod, errType, med) %>%
  # dplyr::filter(!is.na(bestday)) %>%
  as.data.frame()

### the 2nd best day
err_2models_bestday21 <- err_2models %>% 
  ungroup() %>%
  dplyr::filter(errType != 'R2') %>%
  dplyr::group_by(mod, errType) %>%
  arrange(mod, errType, med) %>%
  dplyr::slice(2) %>%
  dplyr::mutate(bestday = lag) %>%
  as.data.frame()

err_2models_bestday22 <- err_2models %>% 
  ungroup() %>%
  dplyr::filter(errType == 'R2') %>%
  dplyr::group_by(mod, errType) %>%
  arrange(mod, errType, desc(med)) %>%
  dplyr::slice(2) %>%
  dplyr::mutate(bestday = lag) %>%
  as.data.frame()

err_2models_bestday2 <- rbind(err_2models_bestday21, err_2models_bestday22)


### plot
(p1 <- ggplot(err_2models, aes(x=lag, y=med))+
    geom_ribbon(aes(ymax=max,ymin=min),alpha=0.3)+
    geom_line()+                  # aes(col = med), 
    scale_color_viridis() + 
    geom_line(aes(y=withinSampErr),col='red')+
    geom_vline(data = err_2models_bestday,  aes(xintercept = bestday), linetype = "dashed", color="blue") + 
    # geom_vline(data = err_2models_bestday2, aes(xintercept = bestday), linetype = "dashed", color="green") +  ## --> not good
    facet_grid(errType~mod, scales = 'free_y')+
    labs(x='Time lag',y='Model Accuracy') +
    theme_bw()
)
```



### moving average of median
  
  The result is not good - give up this option. 
  
```{r}
err_2models_ma <- err_2models %>%
  dplyr::group_by(mod, errType) %>%
  dplyr::mutate(
    med_ma = zoo::rollmean(med, k = 3, fill = 'extend')) %>% ## fill = NA
  arrange(mod, errType, lag)

err_2models_ma_bestday <- err_2models_ma %>% 
  dplyr::mutate(mod = as.factor(mod), errType = as.factor(errType)) %>%
  group_by(mod, errType) %>%
  dplyr::mutate(best    = ifelse(errType != 'R2', min(med_ma), max(med_ma, na.rm = T)),
                bestday = ifelse(med_ma == best, lag, NA)) %>%
  dplyr::filter(!is.na(bestday))

  
  
# (p1 <- ggplot(err_2models_ma, aes(x=lag, y=med))+
#     geom_ribbon(aes(ymax=max,ymin=min),alpha=0.3)+
#     geom_line(size = 2)+                  # aes(col = med), 
#     geom_line(aes(y = med_ma),col = 'red')+ # , col = med_ma
#     scale_color_viridis() + 
#     # geom_ma(ma_fun = SMA, n = 3) + # Plot 30-day SMA
#     # geom_line(aes(y=withinSampErr),col='red')+
#     geom_vline(data = err_2models_ma_bestday, 
#                aes(xintercept = bestday), linetype = "dashed", color="blue") + 
#     facet_grid(errType~mod, scales = 'free_y')+
#     labs(x='Time lag',y='Model Accuracy') +
#     theme_bw()
# )

### --> not that good ......
```



## plot 2

```{r}
### to keep the y-axis at the same scale in all three plots, here we add the max and min value from p1 to p2. 
fdaErr_si <- fdaErr %>%
  group_by(name) %>%
  dplyr::distinct(med)

err_2models_MaxMin <- err_2models %>%
  group_by(errType) %>%
  dplyr::summarise(max = max(max, na.rm = T),
                   min = min(min, na.rm = T)) %>%
  gather(key = maxmin, value = value, max:min) %>%
  dplyr::select(-maxmin) %>%
  merge(., fdaErr_si, by.x = 'errType', by.y = 'name', all.x = T) %>%
  dplyr::rename('name' = 'errType') %>% as.data.frame()

fdaErr2 <- rbind(fdaErr %>% as.data.frame(), err_2models_MaxMin)


(p2 <- fdaErr2 %>% 
  dplyr::mutate(mod = 'FDA') %>% 
  ggplot(aes(x=value))+#geom_freqpoly()+
  geom_histogram(fill='black', alpha=0.3, binwidth = 0.02)+
  geom_vline(aes(xintercept=med),col='black')+
  geom_vline(data=fdaWithin,aes(xintercept=value),col='red')+
    facet_grid(name~mod,scales='free_y')+
  
  coord_flip() +
    labs(x='',y='Count') +
    theme_bw()
)
```



## combine plot 1 and 2
```{r}
(p <- ggarrange(p1,p2,nrow=1, widths = c(2,1)))

ggsave('./figures/outOfSamp_comparison_3models.png', p, width=8, height=4)

```

