---
title: "Untitled"
author: "Yingjie"
date: "07/22/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---



# Set up
```{r Packages}
# To clear your environment 
# remove(list = ls())

library(readxl)
library(tidyverse)
library(dplyr)
library(proj4)
library(stringr)
library(scales)
library(lubridate)

## data describe 
library(summarytools)

library(sf)
library(maps)
library(mapdata)

library(RColorBrewer)
library(viridis)
# devtools::install_github("jaredhuling/jcolors")
library(jcolors)
library(scico) ## colors
```


```{r Dirs}
### Set work dir ----------------------------------------------------------
path <- rstudioapi::getSourceEditorContext()$path
dir  <- dirname(rstudioapi::getSourceEditorContext()$path); dir
dirname(dir)        ## go to parent dir
setwd(dirname(dir)) ## set this parent dir as root dir
getwd()

### the data dir ----------------------------------------------------------
dir.path <- '../Dead_Zone_telecoupling/data/DO/DO_GOM/DO_Integrated_Matli_NCSU'
setwd(dir.path)
getwd()

dir.root   <- dirname(dir) %>% dirname()
dir.fig    <- paste0(dirname(dir), '/hypoxiaMapping/figures/'); dir.fig
dir.output <- './data_cleaned/'

today <- format(Sys.time(), "%Y%m%d"); print(today)

### keep more decimals 
options(digits = 15)
options(pillar.sigfig = 15)
```



# Data
## - All DO data for GEE
  - 1. DO profile data
  - 2. location table for extracting spectral data in GEE
```{r}
### load cleaned data ------------------------------------------------------------
fname <- paste0(dir.output, 'DO_Integrated_sf_sp_final_2000_2019.RData');   fname
load(fname)
names(df_final)

### 1. DO profile data --> 
df_final_do <- df_final %>%
  dplyr::select(YEID, Year, Date, DO, Depth, Temp, Salin, Source, lat, lon) %>% 
  dplyr::mutate(Date = as.Date(Date))


### 2. location table (NOT SURE WE SHOULD INCLUDE hypoxia watch DATA, perhaps NOT at this moment)
df_final_pt <- sp_final %>%
  dplyr::filter(Year >= 2000) %>%
  dplyr::select(YEID, Date, Year, lat, lon) %>%
  distinct(YEID, .keep_all = T) %>%
  dplyr::mutate(Date = as.Date(Date))%>%
  dplyr::mutate(id = row.names(.))

### how many sampling locations in each year?
df_final_pt %>%
  ungroup() %>% dplyr::group_by(Year) %>% tally()

### point to sf
projcrs <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
df_final_pt_sf <- st_as_sf(df_final_pt, coords = c("lon", "lat"), crs = projcrs)
# ggplot() + geom_sf(data = df_final_pt_sf, col = "red", size = 1) + theme_bw()
```





## - 2014 DO data description
```{r}
names(df_final)

### sampling data for 2014 --------------------
df2014 <- df_final %>%
  dplyr::filter(Year == 2014) %>%
  dplyr::filter(nchar(YEID) < 10) %>%
  dplyr::select(YEID, Year, Date, DO, Depth, Temp, Salin, Source, lat, lon, Depth_dem) %>% 
  dplyr::mutate(Date = as.Date(Date))

# dfSummary(df2014)
names(df2014)


### sampling locations that will be used for extracting Spectral_Value from images
df2014_pt <- df2014 %>%
  distinct(YEID, Date, lat, .keep_all = T) %>%
  dplyr::select(YEID, Date, Year, lat, lon) %>%
  arrange(Date, lat, lon) %>%
  dplyr::mutate(id = row.names(.))

projcrs <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
df2014_sf <- st_as_sf(df2014_pt, coords = c("lon", "lat"), crs = projcrs)
# ggplot() + geom_sf() + geom_sf(data = df2014_sf, col = "red", size = 6, alpha=0.6) + theme_bw()
```


  Figure S2. Sampling date at each sampling location (a) and the distribution of the sampling dates. 

```{r - Fig S2}
require("ggrepel") ## for `geom_text_repel`

do <- df2014


### Fig S2b
(s2b <- 
  do %>% 
    ungroup() %>%
    distinct(YEID, Date, .keep_all = T) %>%
    group_by(YEID, Date) %>% tally() %>%
    as.data.frame() %>%
    ggplot()+
    geom_col(aes(x = Date, y = n)) +
    ggtitle('Number of sampling locations by date in 2014') + 
    ylab('Count') +
    theme_bw()
)
  
  
### Fig S2a
doDmax <- do %>% 
  ungroup() %>%
  group_by(YEID) %>%
  slice(which.max(Depth))

(s2a <- 
  doDmax %>%
    dplyr::mutate(mm = as.factor(paste(month(Date), day(Date), sep = '-')),
                  date= as.numeric(Date)) %>%
    ggplot(aes(x = lon, y = lat, label = mm))+ ## , color = date
    geom_point(aes(fill = DO), size = 3, colour = "NA",
               # alpha = 0.6, 
               shape = 21, show.legend = T) +
    geom_text(aes(color = date),show.legend = F, 
              nudge_y = -0.04,
              nudge_x = 0.15) +
    scico::scale_color_scico(palette = "roma", direction = -1) +
    scico::scale_fill_scico(palette = "roma") +
    ylab('Latitude') + xlab('Longitude') +
    labs(fill = 'DO (mg/l)') +
    ggtitle('Sampling date in 2014') +
    theme_bw() +
    theme(legend.position=c(0.945, 0.19), legend.key.height = unit(0.35, 'cm'),
          legend.background = element_rect(fill='transparent')))
  


ggpubr::ggarrange(s2a, s2b, labels = c('(a)', '(b)'), nrow = 2,
                  font.label = list(color = "black", face = "plain", family = NULL, position = "top"))

fname <- paste0(dir.fig, 'Fig S2.png'); fname
ggsave(filename = fname, plot = last_plot(), bg = "transparent",
       width = 7, height = 7, units = 'in', dpi = 300)
```



```{r - Fig S3}
## Figure S3. The total number of DO samples in the profile at each sampling location. -------------
do %>% group_by(YEID, lat, lon) %>% tally() %>%
  dplyr::filter(nchar(YEID) < 10) %>%
  ggplot()+
  geom_text(aes(x = lon, y = lat, label = n, size = n), show.legend = F) +
  ggtitle('Number of samples at each location in 2014') +
  ylab('Latitude') + xlab('Longitude') +
  theme_bw()


fname <- paste0(dir.fig, 'Fig S3.png'); fname
ggsave(filename = fname, plot = last_plot(), bg = "transparent",
       width = 7, height = 3.5, units = 'in', dpi = 300)
```



```{r - Fig S4}
## Figure S4. DO and water temperature in the profile at different depths. -------------------------
do %>%
  ggplot()+
  geom_point(aes(x = DO, y = -Depth, color = Temp), show.legend = T) +
  facet_wrap(~Date) +
  # scico::scale_color_scico(palette = "roma") +
  scale_color_viridis(option="inferno", direction = 1) +
  geom_vline(xintercept = 2, 'dash') +
  ylab('Sampling depth (m)') + xlab('DO (mg/l)') +
  ggtitle('DO and water temperature at different sampling depth') +
  theme_bw()
fname <- paste0(dir.fig, 'Fig S4.png'); fname
ggsave(filename = fname, plot = last_plot(), bg = "transparent",
       width = 8, height = 8, units = 'in', dpi = 300)
```
