---
title: "Untitled"
author: "Yingjie"
date: "11/1/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---



# Package
```{r}
remove(list = ls())

library(readr)
library(lubridate)
library(tidyverse)
library(cowplot)

## DF to Raster
library(sp)
library(raster)


## Plot maps
library(tmap)
library(RColorBrewer)
library(grid) ## put plots in a panel


## a function to only keep 'dead zone' cells, while remove all other cells
func_dz_raster <- function(r){
  r[r > 2]  <- NA
  r[r <= 2] <- 1    ## 
  return(r)
}



## versions of revision 
postfix <- ""     ## first submission
postfix <- "_R1"  ## first revision
```


# Data


```{r - Load RF area data}

## temporal change of dz area in 2014 ----------------------------------------------------
# csv <- './data/results_RF/dz_area_overTimee_geeRF.csv'
# csv <- './data/results_RF/dz_area_overTime_geeRF_10d.csv'
csv <- './data/results_RF/dz_area_overTime_geeRF_10d_R1.csv' ## 2022-05-12

area_dz_rf <- read_csv(csv) %>%
  rename_at(vars(starts_with("system")), ~'date') %>%
  dplyr::rename(area = Area) %>%
  dplyr::mutate(date = as.Date(date, "%B %d, %Y"), 
                model = 'RF') %>%
  dplyr::select(model, date, area)
```




```{r - Load FDA and LLR data}
# ## load FR data
# load('./data/FRmapDat.Rdata')
# head(FRmapDat)
# # str(FRmapDat)
# 
# 
# ## load LL data
# load('./data/LLmapDat.Rdata')
# head(LLmapDat)
# # str(LLmapDat)


##
load('./data/FRmapDatFull.Rdata') # --> FRmapDatFull
head(FRmapDatFull)
load('./data/LLmapDatFull.Rdata') # --> LLmapDatFull
head(LLmapDatFull)
```



```{r - List data}

dat_ls <- ls(pattern = "DatFull$"); dat_ls
which_dat_ls <- gsub("mapDatFull", "", dat_ls)


## --> 2nd to choose ----------------------->
which_do <- 'predDO'


## --> 3rd no need to action --------------|
d <- get(dat_ls[1])  ## pick anyone of the two datasets
doy_ls <- unique(d$doy) %>% as.character(); doy_ls

```



*test 1* - df to raster
```{r eval=FALSE, include=FALSE}
## --> 1st to choose -----------------------> 
dat <- FRmapDatFull; which_dat <- 'FR'
dat <- LLmapDatFull; which_dat <- 'LL'


doy_id <- '152'
date_ini <- doy_id; date_ini

df <- dat %>%
  dplyr::filter(doy == doy_id) %>%
  dplyr::select(lon, lat, predDO)

## dataframe with coordinates to raster 
coordinates(df) <- ~lon+lat 
gridded(df) <- TRUE
# class(df)
# str(df@data)

r <- raster(df) 
class(r)
res(r)

## plot raster
plot(r)

## write it as a geoTIFF
fname <- paste0("./data/results/", which_dat, "map_", which_do, '_', date_ini, ".tif"); fname
# writeRaster(r, filename = fname, overwrite=TRUE)


```


*test 2* - df to raster

  This is the approach provided by Sam. It works but can not be read in and plot using `tmap` package.
  
```{r eval=FALSE, include=FALSE}
library(sp)
library(raster)

#Get info needed for transforming points to rasters
tempRaster <- brick("./data/2014_121.tif") #Read in first combined tif file
tempRes <- res(tempRaster); tempRes #Resolution
tempCRS <- crs(tempRaster) #CRS
tempExtent <- extent(tempRaster) #Extent

#Not sure what your workflow is, but say you only wanted a raster for the first doy:
df       <- dplyr::filter(dat, doy == doy_id) #Choose only first slice
dfCoords <- df[,c('lon','lat')]
dfData   <- df %>% dplyr::select(predDO) #Get rid of extra info
dfsp     <- SpatialPointsDataFrame(coords = dfCoords, data = dfData, proj4string=tempCRS) #Convert to sp object

r <- raster(crs = tempCRS, vals = NA, resolution = tempRes, ext = tempExtent) %>%
  rasterize(dfsp, .)

plot(r$predDO) #Works

#Now that it's been converted, you can save it in whatever form you want using writeRaster()
## write it as a geoTIFF
fname <- paste0("./data/results/", which_dat, "map_", which_do, '_', date_ini, ".tif"); fname
# writeRaster(r, filename = fname, overwrite=TRUE)
```


*test 3* - area calculation
```{r eval=FALSE, include=FALSE}

## Here we take the result from GEE as the reference for testing different methods 

r_name <- './data/data_from_gee/predict_do_maps_lag10d/do_map_20140721.tif'
r <- raster(r_name)
# r <- brick(r_name)
r_dz <- func_dz_raster(r = r)
plot(r)
plot(r_dz, col = 'red', legend = F)



## a summary of all the methods and the results ----------

## GEE:        12366 km2
## approach 1: 12404 km2 ## The best --> to use this one for the following calculations
## approach 2: wrong
## approach 3: 12415 km2
## approach 4: 12434 km2 (terra)



### approach 1 -------------------------------------------
tapply(area(r_dz), r_dz[], sum)


### approach 2 ------------------------------------------- wrong!!
# r_dzr <- as.data.frame(r_dz); names(r_dzr) <- 'predDO'
# r_dzr %>%
#   group_by(predDO) %>%
#   tally() %>%
#   mutate(area = n * res(r_dz)[1] * res(r_dz)[2])


### approach 3 -------------------------------------------
# #get sizes of all cells in raster [km2]
# cell_size <- area(r_dz, na.rm=TRUE, weights=FALSE)
# plot(cell_size)
# #delete NAs from vector of all raster cells
# cell_size <- cell_size[!is.na(cell_size)]
# #compute area [km2] of all cells in geo_raster
# raster_area <- length(cell_size)*median(cell_size); raster_area




### approach 3 -------------------------------------------

# library(terra)
### SpatRaster 
# r <- rast(x = r_name)
# r_dz <- func_dz_raster(r = r)
# plot(r_dz, col = 'red', legend = F)
# # summed area in km2
# terra::expanse(r_dz, unit="km", transform=TRUE)

```



```{r - Loop DF and calculate dz area}

area_df <- data.frame()


for (i in 1:length(dat_ls)) {
  
  dat <- get(dat_ls[i])
  which_dat <- which_dat_ls[i]
  
  doy_ls <- unique(dat$doy) %>% as.character(); doy_ls
  
  
  for (doy_id in doy_ls) {
    
    ## - to get the date info
    date_ini     <- as.Date(as.numeric(doy_id), origin = "2014-01-01"); date_ini
    # date_ini     <- format(date_ini, format ='%Y%m%d'); date_ini
    
  
    ## - df to raster -------------------------------------------------- #
    df <- dat %>%
      dplyr::filter(doy == doy_id) %>%
      dplyr::select(lon, lat, all_of(which_do))
    ## dataframe with coordinates to raster 
    coordinates(df) <- ~lon+lat 
    gridded(df) <- TRUE
    r <- raster(df) 
    
    ## - to calculate dz area ------------------------------------------ #
    min_pixel <- min(values(r), na.rm = T)
    if (min_pixel <= 2) {
      r_dz      <- func_dz_raster(r = r)            ## convert pixel with values <= 0 to 1, others as NA
      r_dz_area <- tapply(area(r_dz), r_dz[], sum)  ## get the sum of hypoxia pixels
    } else {
      r_dz_area <- 0
    }
    
    
    ## - put results in a dataframe
    area    <- data.frame(model = which_dat, date = date_ini, area = r_dz_area)
    area_df <- rbind(area_df, area)
  }
  
  
  fname <- paste0('./data/results/', 'dz_area_overTime_', which_dat, 'mapDatFull', postfix, '.csv'); print(fname)
  write.csv(x = area_df, file = fname, row.names = F)

}
```




```{r - Loop DF and save as TIF}

for (i in 1:length(dat_ls)) {
  
  dat <- get(dat_ls[i])
  which_dat <- which_dat_ls[i]
  
  doy_ls <- unique(dat$doy) %>% as.character(); doy_ls
  
  
  for (doy_id in doy_ls) {
    
    ## - to get the date info
    date_ini     <- as.Date(as.numeric(doy_id), origin = "2014-01-01"); date_ini
    date_ini2    <- format(date_ini, format ='%Y%m%d'); date_ini2
    
    ## - only save TIF from 7/21 - 7/31 -------------------------------- #
    if(date_ini < as.Date('2014-07-21') ){ 
      print('skip')
    } else if (date_ini > as.Date('2014-07-31')) {
      print('skip')
    } else {
      print(date_ini)
      ## - df to raster -------------------------------------------------- #
      df <- dat %>%
      dplyr::filter(doy == doy_id) %>%
      dplyr::select(lon, lat, which_do)
      ## dataframe with coordinates to raster 
      coordinates(df) <- ~lon+lat 
      gridded(df) <- TRUE
      r <- raster(df) 
      ## - write it as a geoTIFF
      fname <- paste0("./data/results/daily/", which_dat, "map_", which_do, '_', date_ini2, postfix, ".tif"); fname
      writeRaster(r, filename = fname, overwrite=TRUE)
      }
  }
  
}
```







#  Plot Area time series

## plot each 

```{r - RF}

ggplot(area_dz_rf, aes(x = date, y = area)) +
  geom_point() +
  geom_smooth(method = 'loess', formula = 'y ~ x', color = 'darkorange') +
  ylab('Area (sq km)')+ xlab('Date') +
  theme_bw()

fname <- paste0('./figures/', 'area_dz_overTime_RF.png'); fname
# ggsave(filename = fname, plot = last_plot(), width = 6, height = 4, units = 'in', dpi = 300)



summary(area_dz_rf$area)


# July 26 - August 3
area_dz_rf %>% 
  dplyr::filter(date >= as.Date('2014-07-19'), 
                date <= as.Date('2014-08-15')) %>%
  summary()
  
```




```{r - FDA & LLR}
area_dz_fr <- readr::read_csv(paste0("./data/results/dz_area_overTime_FRmapDatFull", postfix, ".csv"))
area_dz_ll <- readr::read_csv(paste0("./data/results/dz_area_overTime_LLmapDatFull", postfix, ".csv"))
area_dz_2model    <- rbind(area_dz_fr, area_dz_ll)

area_dz_2model %>%
  ggplot(aes(x = date, y = area, color = model)) +
  geom_point() +
  geom_smooth(method = 'loess', formula = 'y~x') +
  ylab('Area (sq km)')+ xlab('Date') +
  theme_bw()


area_dz_2model %>%
  rbind(area_dz_rf) %>%
  ggplot(aes(x = date, y = area, color = model, fill = model)) +
  geom_point() +
  geom_smooth(method = 'loess', formula = 'y~x') +
  ylab('Area (sq km)')+ xlab('Date') +
  theme_bw()
fname <- paste0('./figures/', 'area_dz_overTime_3models_daily', postfix, '.png'); fname
# ggsave(filename = fname, plot = last_plot(), width = 6, height = 4, units = 'in', dpi = 300)
```






## plot all with composite result

  FDA, LLR, RF
  
```{r - Fig 3b}

model_fullname <- c('Lagged Linear Regression', 'Random Forest Regression', 'Functional Data Analysis')

## --> create a time frame, in which put every 10 days as a slot
time_frame <- 
  data.frame(date = seq(as.Date("2014-05-01"), as.Date("2014-09-01"), by="days")) %>%
  dplyr::mutate(y = year(date),
                m = month(date),
                d = day(date),
                b = case_when(d < 11 ~ 1,
                              d < 21 ~ 2,
                              TRUE   ~ 3),
                slot = paste0(y, '-',  m, '-', b, '0') %>% as.Date(., format="%Y-%m-%d")
                  ) %>%
  dplyr::select(date, slot) %>%
  as.data.frame()

## --> get the median value of each 10-day slot, for `LLR` and `FDA`
## --> then row bind with `RFR` data
area_dz_10d_3model <- 
  merge(area_dz_2model, time_frame, by = 'date', all.x = T) %>%
  group_by(model, slot) %>%
  dplyr::summarise(med = median(area, na.rm = T)) %>%
  dplyr::rename(area = med, date = slot) %>%
  as.data.frame() %>%
  rbind(area_dz_rf) %>%
  dplyr::mutate(model = factor(x = model, levels = c('LL', 'RF', 'FR'), labels = c('LLR', 'RFR', 'FDA'))) %>%
  as.data.frame()

str(area_dz_10d_3model)


## - plot 1 - whole time range ---------------------------------------------------------------------
area_dz_10d_3model %>%
  ggplot(aes(x = date, y = area, color = model, fill = model)) +
  geom_point() +
  geom_smooth(method = 'loess', formula = 'y~x') +
  ylab('Area (sq km)')+ xlab('Date') +
  theme_bw() +
  labs(fill = 'Models', color = 'Models') +
  theme(legend.position = c(0.1, 0.85))

fname <- paste0('./figures/', 'area_dz_overTime_3models', postfix, '.png'); fname
# ggsave(filename = fname, plot = last_plot(), width = 7, height = 6, units = 'in', dpi = 300)




## - plot 2 - only 6/1 - 9/1

area_dz_10d_3model %>%
  dplyr::filter(date >= as.Date('2014-06-01'), date <= as.Date('2014-09-01')) %>%
  ggplot(aes(x = date, y = area, color = model, fill = model)) +
  geom_point(show.legend = F, size = 1) +
  geom_smooth(method = 'loess', formula = 'y~x', show.legend = T) +
  geom_vline(xintercept = as.Date('2014-06-09'), linetype = 'dashed', color = 'gray50') +
  geom_vline(xintercept = as.Date('2014-09-11'), linetype = 'dashed', color = 'gray50') +
  ylab('Area (sq km)')+ xlab('Date') +
  theme_bw() +
  labs(fill = 'Models', color = 'Models') +
  theme(legend.position = c(0.1, 0.85), panel.grid.minor = element_blank())
fname <- paste0('./figures/', 'area_dz_overTime_3models_Jun1Sep1', postfix, '.png'); fname
# ggsave(filename = fname, plot = last_plot(), width = 7, height = 6, units = 'in', dpi = 300)




## - plot 2 - only 6/1 - 9/1 -- facet
area_dz_10d_3model %>%
  dplyr::mutate(model = factor(model, levels = c('LLR', 'RFR', 'FDA'), labels = model_fullname)) %>%
  # dplyr::filter(date >= as.Date('2014-05-20'), date <= as.Date('2014-09-03')) %>%
  ggplot(aes(x = date, y = area, color = model, fill = model)) +
  geom_point(show.legend = F, size = 1) +
  geom_smooth(method = 'loess', formula = 'y~x', show.legend = F) +
  geom_vline(xintercept = as.Date('2014-06-09'), linetype = 'dashed', color = 'gray50') +
  geom_vline(xintercept = as.Date('2014-09-11'), linetype = 'dashed', color = 'gray50') +
  # geom_segment(aes(x = as.Date('2014-08-21'), xend = as.Date('2014-07-25'), 
  #                  y = 12000, yend = 13000), show.legend = F,
  #                 arrow = arrow(length = unit(0.5, "cm"))) +
  facet_wrap(~model) + #, scales = 'free_y'
  ylab('Area (sq km)')+ xlab('Date') +
  # ylim(-3000, NA) +
  theme_bw() +
  labs(fill = 'Models', color = 'Models') +
  theme(legend.position = c(0.1, 0.85), 
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.minor = element_blank(), panel.grid.major.x = element_blank())
fname <- paste0('./figures/', 'area_dz_overTime_3models_Jun1Sep1_facet', postfix, '.png'); fname
ggsave(filename = fname, plot = last_plot(), width = 7, height = 3, units = 'in', dpi = 300)
```



```{r - Report the peak area in MS}
###

summary(area_dz_10d_3model$area)


### filter the time range when dz peaks
area_dz_10d_3model_peak <- area_dz_10d_3model %>%
  dplyr::filter(date >= as.Date('2014-07-15'), date <= as.Date('2014-08-15')) 


# x <- area_dz_10d_3model_peak$area
# x[!x %in% boxplot.stats(x)$out]


### get the summary info 
area_dz_10d_3model_peak_sm <- area_dz_10d_3model_peak %>%
  arrange(model, desc(area)) %>%
  group_by(model) %>%
  dplyr::summarise(mean = mean(area, na.rm = T), 
                   # median = median(area, na.rm = T), 
                   sd  = sd(area, na.rm = T),
                   max = max(area, na.rm = T)) %>%
  as.data.frame()
area_dz_10d_3model_peak_sm

### the average dz size across 3 models, and the sd, se
mean(area_dz_10d_3model_peak$area)
sd(area_dz_10d_3model_peak$area)
se <- function(x) sd(x)/sqrt(length(x))
se(area_dz_10d_3model_peak$area)


### to use this package to get the same information 
Rmisc::summarySE(data = area_dz_10d_3model_peak, measurevar="area")
Rmisc::summarySE(data = area_dz_10d_3model_peak, measurevar="area", groupvars=c("model"))
  

### similar as `Rmisc::summarySE`
psych::describeBy(x = area_dz_10d_3model_peak %>% dplyr::select(-date), group="model", mat = T, digits = 2)
```



